name: Release version

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  autoincrement:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Close version
        run: |
          CURRENT_VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=revision -q -DforceStdout)
          BASE_VERSION=${CURRENT_VERSION%-SNAPSHOT} # Remove -SNAPSHOT
          ./mvnw -B --no-transfer-progress versions:set-property -Dproperty=revision -DnewVersion=$BASE_VERSION
          ./mvnw -B --no-transfer-progress versions:commit 
          
          ./mvnw -f examples/pom.xml -B --no-transfer-progress versions:set-property -Dproperty=revision -DnewVersion=$BASE_VERSION
          ./mvnw -f examples/pom.xml -B --no-transfer-progress versions:commit

      - name: Commit changed and create Git tag
        run: |
          VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=revision -q -DforceStdout)
          find . -name 'pom.xml' | xargs git add
          git commit -m "Tagged version v${VERSION} [skip-ci]"
          git push
          
          git tag v$VERSION
          git push origin v$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish version to the Maven Central Repository
        run: ./mvnw -B --no-transfer-progress deploy -P publish -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Increment version and append -SNAPSHOT
        run: |
          NEXT_SNAPSHOT=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=revision -q -DforceStdout | awk -F. -v OFS=. '{$NF += 1 ; print}')-SNAPSHOT
          ./mvnw -B --no-transfer-progress versions:set-property -Dproperty=revision -DnewVersion=$NEXT_SNAPSHOT
          ./mvnw -B --no-transfer-progress versions:commit         
          
          ./mvnw -f examples/pom.xml -B --no-transfer-progress versions:set-property -Dproperty=revision -DnewVersion=$NEXT_SNAPSHOT
          ./mvnw -f examples/pom.xml -B --no-transfer-progress versions:commit
          
          find . -name 'pom.xml' | xargs git add
          git commit -m "Increment version to ${NEXT_SNAPSHOT} [skip-ci]"
          git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
